[agent]
name = "notification"
version = "0.0.1"
description = "Notification agent for crypto tipping results"

[options.MISTRAL_API_KEY]
type = "string"
description = "Mistral API key (free tier)"

[options.MODEL_NAME]
type = "string"
description = "Mistral model to use"
default = "mistral-small"

[options.MODEL_PROVIDER]
type = "string"
description = "Mistral provider"
default = "mistral"

[options.MODEL_TEMPERATURE]
type = "string"
description = "Model temperature"
default = "0.1"

[options.MODEL_MAX_TOKENS]
type = "string"
description = "Maximum tokens"
default = "4000"

[options.CORAL_CONNECTION_URL]
type = "string"
description = "Coral server connection URL"
default = "http://localhost:5555"

[options.TIMEOUT_MS]
type = "string"
description = "Connection timeout in milliseconds"
default = "60000"

[runtimes.executable]
command = ["bash", "-c", "./run_agent.sh main.py"]
